apiVersion: v1
appVersion: "1.2"
description: A Helm chart for Deepstream Intelligent Video Analytics
name: deepstream-analytics
version: 1.0.0
icon: https://storage.googleapis.com/deployment-images/servicedeployed/container_logos/nvidia/nvidia_deepstream_logo.png