{{- if (eq .Values.jvb.service.type "LoadBalancer") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.jvb.fullname" . }}-loadbalancer-ip
  labels:
    {{- include "jitsi-meet.jvb.labels" . | nindent 4 }}
data:
    {{- if .Values.jvb.publicIP }}
    public-ip: '{{ .Values.jvb.publicIP }}'
    {{- else }}
    public-ip: ""
    {{- end }}
{{- end }}