apiVersion: v2
name: jitsi-meet
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.2.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: stable-5963

dependencies:
  - name: prosody
    condition: prosody.enabled
    version: 0.2.0

annotations:
  clouds: aws,google,digitalocean,azure
  ingress: true
  required_fields: sd_value_hostname
  sd_value_jvb_service_type: jvb.service.type
  sd_value_hostname: web.ingress.hostname
  sd_repo_index: 1.0
  sd_port_4443_hidden: "true"

icon: https://storage.googleapis.com/deployment-images/servicedeployed/jitsi-512x512.png
keywords:
  - video
  - streaming
sources:
  - https://jitsi.org/
