apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deepstream-analytics.fullname" . }}-configmap
  labels:
    app.kubernetes.io/name: {{ include "deepstream-analytics.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  {{- range $key, $val := .Values.cameras}}
  {{$key }}: {{$val | quote }}
  {{- end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deepstream-analytics.fullname" . }}-webui-configmap
data:
{{ (.Files.Glob "config/play.html").AsConfig | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deepstream-analytics.fullname" . }}-create-config
data:
{{ (.Files.Glob "config/create_config.py").AsConfig | indent 4 }}
