{{- if .Values.ingress.enabled -}}
{{- $fullName := include "deepstream-analytics.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  {{- with .Values.ingress.annotations }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{ if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
  tls:
  - hosts:
      - {{ .Values.ingress.hostname }}
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $svcPort }}
  {{ else }}
  tls:
    - hosts:
      - {{ .Values.ingress.hostname }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
  {{ end }}
{{- end }}