apiVersion: v1
kind: Service
metadata:
  name: {{ include "deepstream-analytics.fullname" . }}
  labels:
{{ include "deepstream-analytics.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ include "deepstream-analytics.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "deepstream-analytics.fullname" . }}-webui
  labels:
    # App.kubernetes.io.. added by InnovoEdge
    app.kubernetes.io/instance: {{ .Release.Name }}
    name: {{ include "deepstream-analytics.fullname" . }}-webui
spec:
  #type: {{ .Values.service.type }}
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.webuiPort }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.webuinodePort }}
  selector:
    name: {{ include "deepstream-analytics.fullname" . }}-webui
